export const TALMUD_TRACTATES = [
  { id: 'berakhot', nameEn: 'Berakhot', nameHe: 'ברכות', endPage: 64 },
  { id: 'shabbat', nameEn: 'Shabbat', nameHe: 'שבת', endPage: 157 },
  { id: 'eruvin', nameEn: 'Eruvin', nameHe: 'עירובין', endPage: 105 },
  { id: 'pesachim', nameEn: 'Pesachim', nameHe: 'פסחים', endPage: 121 },
  { id: 'shekalim', nameEn: 'Shekalim', nameHe: 'שקלים', endPage: 22 },
  { id: 'yoma', nameEn: 'Yoma', nameHe: 'יומא', endPage: 88 },
  { id: 'sukkah', nameEn: 'Sukkah', nameHe: 'סוכה', endPage: 56 },
  { id: 'beitzah', nameEn: 'Beitzah', nameHe: 'ביצה', endPage: 40 },
  { id: 'roshhashanah', nameEn: 'Rosh Hashanah', nameHe: 'ראש השנה', endPage: 35 },
  { id: 'taanit', nameEn: 'Taanit', nameHe: 'תענית', endPage: 31 },
  { id: 'megillah', nameEn: 'Megillah', nameHe: 'מגילה', endPage: 32 },
  { id: 'moedkhatan', nameEn: 'Moed Katan', nameHe: 'מועד קטן', endPage: 29 },
  { id: 'chagigah', nameEn: 'Chagigah', nameHe: 'חגיגה', endPage: 27 },
  { id: 'yevamot', nameEn: 'Yevamot', nameHe: 'יבמות', endPage: 122 },
  { id: 'ketubot', nameEn: 'Ketubot', nameHe: 'כתובות', endPage: 112 },
  { id: 'nedarim', nameEn: 'Nedarim', nameHe: 'נדרים', endPage: 91 },
  { id: 'nazir', nameEn: 'Nazir', nameHe: 'נזיר', endPage: 66 },
  { id: 'sotah', nameEn: 'Sotah', nameHe: 'סוטה', endPage: 49 },
  { id: 'gittin', nameEn: 'Gittin', nameHe: 'גיטין', endPage: 90 },
  { id: 'kiddushin', nameEn: 'Kiddushin', nameHe: 'קידושין', endPage: 82 },
  { id: 'bavakamma', nameEn: 'Bava Kamma', nameHe: 'בבא קמא', endPage: 119 },
  { id: 'bavametzia', nameEn: 'Bava Metzia', nameHe: 'בבא מציעא', endPage: 119 },
  { id: 'bavabatra', nameEn: 'Bava Batra', nameHe: 'בבא בתרא', endPage: 176 },
  { id: 'sanhedrin', nameEn: 'Sanhedrin', nameHe: 'סנהדרין', endPage: 113 },
  { id: 'makkot', nameEn: 'Makkot', nameHe: 'מכות', endPage: 24 },
  { id: 'shevuot', nameEn: 'Shevuot', nameHe: 'שבועות', endPage: 49 },
  { id: 'avodahzarah', nameEn: 'Avodah Zarah', nameHe: 'עבודה זרה', endPage: 76 },
  { id: 'horayot', nameEn: 'Horayot', nameHe: 'הוריות', endPage: 14 },
  { id: 'zevachim', nameEn: 'Zevachim', nameHe: 'זבחים', endPage: 120 },
  { id: 'menachot', nameEn: 'Menachot', nameHe: 'מנחות', endPage: 110 },
  { id: 'chullin', nameEn: 'Chullin', nameHe: 'חולין', endPage: 142 },
  { id: 'bekhorot', nameEn: 'Bekhorot', nameHe: 'בכורות', endPage: 61 },
  { id: 'arakhin', nameEn: 'Arakhin', nameHe: 'ערכין', endPage: 34 },
  { id: 'temurah', nameEn: 'Temurah', nameHe: 'תמורה', endPage: 34 },
  { id: 'keritot', nameEn: 'Keritot', nameHe: 'כריתות', endPage: 28 },
  { id: 'meilah', nameEn: 'Meilah', nameHe: 'מעילה', endPage: 22 },
  { id: 'niddah', nameEn: 'Niddah', nameHe: 'נידה', endPage: 73 }
];
